absolute_urls: false
timezone: 'Europe/Vienna'
default_locale: 'de_AT'

languages:
  supported:
    - de
    - sk
    - hu
    - en
  include_default_lang: false

home:
  alias: '/home'

pages:
  theme: ladislavpapp
  markdown:
    extra: true
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true
  collections:
    jquery: theme://vendors/jquery/dist/jquery.min.js

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true
